In [ ]:
import time
import requests
from IPython.display import clear_output
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
base_url = 'https://www.makaan.com/hyderabad-residential-property/buy-property-in-hyderabad-city?page='

own = []   
bhk = []
prz = []
sqt = []
loc = []
stat = []
pps = []

for i in range(1,11):
  time.sleep(3)

  print(f'Going to scrape data from {i} page')
  clear_output(wait=True)
  url = base_url+str(i)+'&_=1625014769303'
  req = requests.get(url)
  soup = BeautifulSoup(req.text,'html')

Going to scrape data from 10 page

In [ ]:
 #owner info
ow_info=soup.findAll('span',attrs={'class':'seller-type'})
for j in ow_info:
    own.append(j.text)

  #bhk info
bhk_info = soup.findAll('div',attrs={'class':'title-line'})
for j in bhk_info:
    bhk.append(j.strong.span.text)

  #price info
p_info = soup.findAll('div',attrs={'data-type':'price-link'})
for j in p_info:
    prz.append(j.text)

  #size info
s_info = soup.findAll("td",attrs={'class':'size'})
for j in s_info:
    sqt.append(j.text)
  
  #location info
loc_info = soup.findAll('span',attrs={'itemprop':'addressLocality'})
for j in loc_info:
    loc.append(j.text)
  
  #status info

st_info = soup.findAll('tr',attrs={'class':'hcol w44'})
for j in st_info:
    stat.append(j.text)

pps_info = soup.findAll('td',attrs={'class':'lbl rate'})
for j in pps_info:
    pps.append(j.text)

    #price per sqft info

In [ ]:
pd.DataFrame({'Owner_info':own,'Bhk_info' : bhk,'Price': prz,'Locality' : loc,'Area_sqft' : sqt,'Status':stat,'price_per_sqrt':pps})

   Owner_info Bhk_info  ...                                 Status price_per_sqrt
0       OWNER       2   ...  Under ConstructionConstruction Status  3,529 / sq ft
1       OWNER       2   ...  Under ConstructionConstruction Status  3,529 / sq ft
2       OWNER       2   ...  Under ConstructionConstruction Status  3,529 / sq ft
3       OWNER       3   ...  Under ConstructionConstruction Status  2,368 / sq ft
4       OWNER       3   ...  Under ConstructionConstruction Status  2,368 / sq ft
5       OWNER       3   ...  Under ConstructionConstruction Status  2,368 / sq ft
6       OWNER       2   ...  Under ConstructionConstruction Status  2,222 / sq ft
7       OWNER       3   ...  Under ConstructionConstruction Status  2,307 / sq ft
8       OWNER       3   ...  Under ConstructionConstruction Status  2,307 / sq ft
9       OWNER       3   ...  Under ConstructionConstruction Status  2,307 / sq ft
10      OWNER       3   ...  Under ConstructionConstruction Status  2,307 / sq ft
11      OWNER       3   ...  Under ConstructionConstruction Status  3,548 / sq ft
12      OWNER       2   ...  Under ConstructionConstruction Status  3,529 / sq ft
13      OWNER       3   ...  Under ConstructionConstruction Status  2,368 / sq ft
14      OWNER       2   ...  Under ConstructionConstruction Status  3,529 / sq ft
15      OWNER       3   ...  Under ConstructionConstruction Status  3,548 / sq ft
16      OWNER       3   ...  Under ConstructionConstruction Status  2,368 / sq ft
17      OWNER       2   ...  Under ConstructionConstruction Status  3,461 / sq ft
18      OWNER       3   ...  Under ConstructionConstruction Status  2,368 / sq ft
19      OWNER       3   ...  Under ConstructionConstruction Status  2,307 / sq ft

[20 rows x 7 columns]